import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'stickzahl-und-preis-kalkulator-stickerei';
const title = 'Kalkulator für Stickzahl und Preis';
const description = 'Schätze Stickzahl, Produktionszeit und einen Arbeitsgrundpreis anhand von Designgröße, Stichdichte, Farben, Geschwindigkeit und Stundenlohn.';
const faq = [
  { question: 'Wie funktioniert die Schätzung der Stickzahl?', answer: 'Der Rechner multipliziert die bestickte Fläche mit dem Quadrat der Stichdichte und wendet anschließend einen Faktor für die Stichart an. Das ergibt eine vergleichbare Arbeitsmenge, keine Vorhersage der Maschinendatei.' },
  { question: 'Warum verändert die Stichart die Schätzung?', answer: 'Laufstich, Satinstich, Füllstich und Tatami legen den Faden unterschiedlich ab. Ein transparenter relativer Faktor macht sichtbar, dass dichtere Flächen mehr Produktionsaufwand bedeuten.' },
  { question: 'Verändert die Farbanzahl die Stichzahl?', answer: 'Nein. Die Farbanzahl fügt nur Umrüstzeit hinzu. Für jeden Wechsel nach der ersten Farbe rechnet das Modell 1,75 Minuten als Planungsannahme.' },
  { question: 'Ist der berechnete Preis ein Angebot?', answer: 'Nein. Es ist eine Arbeitszeitschätzung mit dem eingegebenen Stundenlohn. Garn, Vlies, Digitalisierung, Einrichtung, Nacharbeit, Gemeinkosten, Steuer und Gewinn sind nicht enthalten.' },
];
const howTo = [
  { name: 'Design messen', text: 'Gib Breite und Höhe der fertigen Stickfläche in Zentimetern ein. Verwende die bestickte Fläche statt der gesamten Rahmengröße.' },
  { name: 'Stichplan beschreiben', text: 'Wähle die vorherrschende Stichart, gib die Dichte in Stichen pro Zentimeter ein und zähle die Garnfarben.' },
  { name: 'Produktionsannahmen eingeben', text: 'Gib Maschinengeschwindigkeit in Stichen pro Minute und deinen Arbeitslohn pro Stunde ein. Verwende eine einheitliche Währung.' },
  { name: 'Planungswert lesen', text: 'Vergleiche gleichwertige Stiche, Produktionszeit, Einrichtungszeit und Arbeitsgrundpreis vor der Digitalisierung oder Angebotserstellung.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'de' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Forme deinen Stichplan im Stickrahmen und sieh den Produktionsaufwand und Arbeitswert.', stageLabel: 'Der Stickrahmen', controlsLabel: 'Stichplan erstellen', resultLabel: 'Arbeitsgrundpreis', widthLabel: 'Designbreite', heightLabel: 'Designhöhe', densityLabel: 'Stichdichte', stitchLabel: 'Vorherrschende Stichart', coloursLabel: 'Garnfarben', speedLabel: 'Maschinengeschwindigkeit', rateLabel: 'Stundenlohn', widthHint: 'bestickte Fläche in cm', heightHint: 'bestickte Fläche in cm', densityHint: 'Stiche pro cm', coloursHint: 'erste Farbe braucht keinen Wechsel', speedHint: 'Stiche pro Minute', rateHint: 'deine Währung pro Stunde', stitchRunning: 'Laufstich', stitchSatin: 'Satinstich', stitchFill: 'Füllstich', stitchTatami: 'Tatami Füllung', stitchRunningNote: 'Leichte Konturen und Schrift mit geringer Abdeckung.', stitchSatinNote: 'Glatte Säulen und Ränder mit konzentriertem Fadenweg.', stitchFillNote: 'Dichte Abdeckung mit mehr Garn und Produktionsaufwand.', stitchTatamiNote: 'Geschichtete Füllung mit dem höchsten Planungsfaktor.', selectStitch: 'Stichart wählen', emptyResult: 'Gib einen Stichplan ein, um den Rahmen zu aktivieren.', stitchesUnit: 'gleichwertige Stiche', minutesUnit: 'Minuten', hoursUnit: 'Stunden', priceUnit: 'Währungseinheiten', areaLabel: 'Bestickte Fläche', effectiveLabel: 'Gleichwertige Stiche', stitchTimeLabel: 'Stickzeit', productionLabel: 'Produktionszeit', setupLabel: 'Farbeneinrichtung', changesLabel: 'Farbwechsel', basePriceLabel: 'Arbeitsgrundpreis', estimateBadge: 'Schätzung bereit', attentionBadge: 'Größe prüfen', warningHighVolume: 'Große Stichmenge. Vor einem Angebot eine echte Maschinenprobe machen.', warningLongRun: 'Langer Produktionslauf. Rahmung, Fadenrisse und Fertigstellung separat prüfen.', invalidMessage: 'Verwende positive Werte für Größe, Dichte, Geschwindigkeit und Stundenlohn.', formulaTitle: 'Was wird gezählt', formulaText: 'Fläche mal Dichte zum Quadrat ergibt die Abdeckungsbasis. Der Stichfaktor macht daraus gleichwertige Stiche; jeder Farbwechsel nach der ersten Farbe fügt 1,75 Minuten hinzu.', noteTitle: 'Grenze der Planung', noteText: 'Dies ist ein transparenter Rechner, keine digitalisierte Maschinendatei und kein fertiges Angebot. Ergänze Material, Einrichtung, Fertigstellung, Gemeinkosten, Steuer und Marge selbst.', reset: 'Beispiel zurücksetzen', copied: 'Zusammenfassung kopiert', copySummary: 'Zusammenfassung kopieren', canvasAlt: 'Stickrahmen aus Stoff mit Fadenlinien für die aktuelle Dichte',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Stickzahl und Arbeitsgrundpreis für Stickerei schätzen', level: 2 },
  { type: 'paragraph', html: 'Bei einem Stickdesign gibt es zwei Planungsfragen: Wie viel Fadenarbeit steckt im Motiv und wie lange sind Maschine und Bedienperson gebunden? Dieser Rechner hält beides sichtbar und verwandelt Fläche, Dichte, Stichart, Farben, Geschwindigkeit und Stundenlohn in einen vergleichbaren Planungswert.' },
  { type: 'title', text: 'Das Modell für die Stichzahl', level: 3 },
  { type: 'paragraph', html: 'Die Basis ist die bestickte Fläche multipliziert mit dem Quadrat der Dichte in Stichen pro Zentimeter. Ein relativer Faktor berücksichtigt die Stichfamilie: Laufstich ist leichter, Satin der Bezugspunkt, Füllung und Tatami sind zunehmend dichte Planungsfälle. Es handelt sich um gleichwertigen Arbeitsaufwand, nicht um die exakte Zahl aus einer Digitalisierungssoftware.' },
  { type: 'table', headers: ['Eingabe', 'Was sie verändert', 'Was sie nicht verspricht'], rows: [['Breite und Höhe', 'Abdeckungsfläche und Basisstichzahl', 'Den exakten Umriss einer digitalisierten Datei'], ['Dichte und Stichart', 'Gleichwertige Fadenarbeit und Maschinenzeit', 'Eine passende Qualitätseinstellung für jeden Stoff'], ['Farben', 'Wechselzeit nach der ersten Farbe', 'Die Zahl von Trims oder Fadenrissen'], ['Geschwindigkeit und Lohn', 'Produktionsdauer und Arbeitswert', 'Ein fertiges Kundenangebot']] },
  { type: 'title', text: 'Aus einer Schätzung einen verantwortlichen Preis machen', level: 3 },
  { type: 'paragraph', html: 'Der angezeigte Preis ist nur Arbeitszeit mal Stundenlohn. Ein echtes Angebot sollte Digitalisierung, Garn, Vlies, Einspannen, Maschineneinrichtung, Probestücke, Abschneiden, Nacharbeit, Fertigstellung, Gemeinkosten, Steuer und Gewinn enthalten. Halte diese Posten getrennt, damit eine kleine Stichzahl keine aufwendige Vorbereitung versteckt.' },
  { type: 'tip', title: 'Plan vor dem Angebot testen', html: 'Führe eine repräsentative Probe auf dem vorgesehenen Stoff und Vlies aus. Vergleiche Zeit und Fadenverhalten mit der Schätzung und passe deine lokalen Geschwindigkeits- und Einrichtungsannahmen an.' },
  { type: 'title', text: 'Die Produktionsaufteilung lesen', level: 3 },
  { type: 'list', items: ['Gleichwertige Stiche zeigen den Abdeckungsaufwand nach Anwendung des Stichfaktors.', 'Produktionszeit ist gleichwertige Stichzahl geteilt durch Maschinengeschwindigkeit.', 'Farbeneinrichtung fügt nach der ersten Farbe je Wechsel 1,75 Minuten hinzu.', 'Der Arbeitsgrundpreis ist die Gesamtzeit geteilt durch 60 und multipliziert mit dem Stundenlohn.'] },
] };
