import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'calculadora-puntadas-precio-bordado';
const title = 'Calculadora de puntadas y precio de bordado';
const description = 'Estima las puntadas, el tiempo de producción y un precio base de mano de obra a partir del tamaño, la densidad, los colores, la velocidad y la tarifa.';
const faq = [
  { question: '¿Cómo funciona la estimación de puntadas?', answer: 'La calculadora multiplica el área bordada por el cuadrado de la densidad de puntadas y aplica después un factor según el tipo de puntada. El resultado es una carga de trabajo equivalente para comparar producciones, no una predicción del archivo de máquina.' },
  { question: '¿Por qué cambia la estimación según la puntada?', answer: 'La puntada corrida, el satén, el relleno y el tatami colocan el hilo de forma distinta. El factor relativo muestra de manera transparente que una cobertura más densa requiere más trabajo de producción.' },
  { question: '¿La cantidad de colores cambia el número de puntadas?', answer: 'No. Los colores solo añaden tiempo de cambio. El modelo reserva 1,75 minutos por cada cambio después del primer color como supuesto de planificación.' },
  { question: '¿El precio calculado es un presupuesto?', answer: 'No. Es una estimación de mano de obra basada en la tarifa horaria indicada. No incluye hilo, estabilizador, digitalización, preparación, montaje, remates, gastos generales, impuestos ni margen.' },
];
const howTo = [
  { name: 'Mide el diseño', text: 'Introduce el ancho y el alto bordados en centímetros. Usa el área que llevará puntadas, no el tamaño completo del bastidor.' },
  { name: 'Describe el plan de puntadas', text: 'Elige el tipo dominante, indica la densidad en puntadas por centímetro y cuenta los colores de hilo.' },
  { name: 'Añade tus supuestos', text: 'Introduce la velocidad en puntadas por minuto y tu tarifa de mano de obra por hora. Mantén una sola unidad monetaria.' },
  { name: 'Lee la estimación', text: 'Usa las puntadas equivalentes, el tiempo de producción, la preparación y el precio base para comparar diseños antes de digitalizar o presupuestar.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'es' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Dale forma a tu plan de puntadas en el bastidor y descubre el esfuerzo de producción y su valor de mano de obra.', stageLabel: 'El bastidor de puntadas', controlsLabel: 'Crea el plan de puntadas', resultLabel: 'Estimación base de mano de obra', widthLabel: 'Ancho del diseño', heightLabel: 'Alto del diseño', densityLabel: 'Densidad de puntada', stitchLabel: 'Puntada dominante', coloursLabel: 'Colores de hilo', speedLabel: 'Velocidad de máquina', rateLabel: 'Tarifa por hora', widthHint: 'área bordada en cm', heightHint: 'área bordada en cm', densityHint: 'puntadas por cm', coloursHint: 'el primer color no necesita cambio', speedHint: 'puntadas por minuto', rateHint: 'tu moneda por hora', stitchRunning: 'Puntada corrida', stitchSatin: 'Puntada satén', stitchFill: 'Puntada de relleno', stitchTatami: 'Relleno tatami', stitchRunningNote: 'Contornos y letras ligeras con poca cobertura.', stitchSatinNote: 'Columnas y bordes suaves con un recorrido concentrado.', stitchFillNote: 'Cobertura sólida que añade hilo y esfuerzo de producción.', stitchTatamiNote: 'Relleno por capas con el factor de planificación más alto.', selectStitch: 'Elige un tipo de puntada', emptyResult: 'Introduce un plan para despertar el bastidor.', stitchesUnit: 'puntadas equivalentes', minutesUnit: 'minutos', hoursUnit: 'horas', priceUnit: 'unidades monetarias', areaLabel: 'Área bordada', effectiveLabel: 'Puntadas equivalentes', stitchTimeLabel: 'Tiempo de puntada', productionLabel: 'Tiempo de producción', setupLabel: 'Preparación de colores', changesLabel: 'Cambios de color', basePriceLabel: 'Estimación base de mano de obra', estimateBadge: 'Estimación lista', attentionBadge: 'Revisa la escala', warningHighVolume: 'Gran volumen de puntadas. Haz una prueba real antes de presupuestar.', warningLongRun: 'Producción larga. Revisa por separado el bastidor, las roturas y los remates.', invalidMessage: 'Usa valores positivos para tamaño, densidad, velocidad y tarifa horaria.', formulaTitle: 'Qué se cuenta', formulaText: 'El área por la densidad al cuadrado crea una base de cobertura. El factor de puntada la convierte en puntadas equivalentes y cada cambio después del primer color añade 1,75 minutos.', noteTitle: 'Límite de planificación', noteText: 'Es una calculadora transparente, no un archivo de máquina digitalizado ni un presupuesto final. Añade por tu cuenta materiales, preparación, remates, gastos, impuestos y margen.', reset: 'Restablecer ejemplo', copied: 'Resumen copiado', copySummary: 'Copiar resumen', canvasAlt: 'Bastidor de bordado de tela con líneas de hilo que muestran la densidad actual',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Cómo estimar puntadas y precio de mano de obra de bordado', level: 2 },
  { type: 'paragraph', html: 'Un diseño de bordado plantea dos preguntas distintas: cuánta labor de hilo contiene el motivo y cuánto tiempo ocuparán la máquina y la persona que la maneja. Esta calculadora mantiene ambas visibles y transforma tamaño, densidad, puntada, colores, velocidad y tarifa en una cifra de planificación comparable.' },
  { type: 'title', text: 'El modelo de puntadas', level: 3 },
  { type: 'paragraph', html: 'La base es el área bordada multiplicada por el cuadrado de la densidad en puntadas por centímetro. Un factor relativo tiene en cuenta la familia de puntada: la corrida es más ligera, el satén sirve de referencia y los rellenos son casos de planificación progresivamente más densos. Es una estimación del trabajo equivalente, no el recuento exacto que exporta un programa de digitalización.' },
  { type: 'table', headers: ['Entrada', 'Qué cambia', 'Qué no promete'], rows: [['Ancho y alto', 'Área de cobertura y puntadas base', 'El contorno exacto de un archivo digitalizado'], ['Densidad y puntada', 'Trabajo equivalente y tiempo de máquina', 'Un ajuste universal para cualquier tejido'], ['Colores', 'Tiempo de cambio después del primer color', 'El número de recortes o roturas de hilo'], ['Velocidad y tarifa', 'Duración y valor de mano de obra', 'Un presupuesto final para el cliente']] },
  { type: 'title', text: 'Convierte una estimación en un precio responsable', level: 3 },
  { type: 'paragraph', html: 'El precio mostrado solo multiplica el tiempo de trabajo por tu tarifa horaria. Un presupuesto real debe sumar digitalización, hilo, estabilizador, bastidor, preparación, muestras, recortes, repeticiones, remates, gastos generales, impuestos y margen. Mantenerlos separados evita que un recuento bajo oculte una preparación laboriosa.' },
  { type: 'tip', title: 'Prueba el plan antes de presupuestar', html: 'Haz una muestra representativa sobre el tejido y el estabilizador previstos. Compara su tiempo y el comportamiento del hilo con la estimación y ajusta tus supuestos locales de velocidad y preparación.' },
  { type: 'title', text: 'Cómo leer el desglose de producción', level: 3 },
  { type: 'list', items: ['Las puntadas equivalentes muestran la carga de cobertura después de aplicar el factor.', 'El tiempo de producción son las puntadas equivalentes divididas por la velocidad.', 'La preparación de color añade 1,75 minutos por cada cambio después del primero.', 'La estimación base es el tiempo total dividido por 60 y multiplicado por la tarifa horaria.'] },
] };
