import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'estimateur-points-prix-broderie';
const title = 'Estimateur de points et de prix de broderie';
const description = 'Estimez le nombre de points, le temps de production et un coût de main-d\'oeuvre à partir de la taille, de la densité, des couleurs, de la vitesse et du tarif horaire.';
const faq = [
  { question: 'Comment fonctionne l\'estimation du nombre de points ?', answer: 'L\'estimateur multiplie la surface brodée par le carré de la densité de points, puis applique un facteur selon le type de point. Le résultat compare la charge de production, sans prédire le fichier machine.' },
  { question: 'Pourquoi le type de point change-t-il le résultat ?', answer: 'Le point courant, le satin, le remplissage et le tatami déposent le fil différemment. Le facteur relatif rend visible le travail supplémentaire d\'une couverture plus dense.' },
  { question: 'Le nombre de couleurs change-t-il le nombre de points ?', answer: 'Non. Les couleurs ajoutent seulement du temps de changement. Le modèle compte 1,75 minute pour chaque changement après la première couleur comme hypothèse de planification.' },
  { question: 'Le prix calculé est-il un devis ?', answer: 'Non. Il s\'agit d\'une estimation de main-d\'oeuvre basée sur le tarif saisi. Le fil, le stabilisateur, la numérisation, la préparation, la finition, les frais, les taxes et la marge ne sont pas inclus.' },
];
const howTo = [
  { name: 'Mesurer le motif', text: 'Saisissez la largeur et la hauteur brodées en centimètres. Utilisez la surface cousue et non la taille complète du cadre.' },
  { name: 'Décrire le plan de points', text: 'Choisissez le type dominant, indiquez la densité en points par centimètre et comptez les couleurs de fil.' },
  { name: 'Ajouter les hypothèses', text: 'Saisissez la vitesse en points par minute et votre tarif de main-d\'oeuvre par heure. Gardez une seule unité monétaire.' },
  { name: 'Lire la planification', text: 'Utilisez les points équivalents, le temps de production, le temps de préparation et le coût de base pour comparer les motifs.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'fr' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Composez votre plan de points dans le cadre et voyez l\'effort de production ainsi que sa valeur de main-d\'oeuvre.', stageLabel: 'Le cadre de broderie', controlsLabel: 'Construire le plan de points', resultLabel: 'Coût de main-d\'oeuvre', widthLabel: 'Largeur du motif', heightLabel: 'Hauteur du motif', densityLabel: 'Densité de points', stitchLabel: 'Type de point dominant', coloursLabel: 'Couleurs de fil', speedLabel: 'Vitesse de la machine', rateLabel: 'Tarif horaire', widthHint: 'surface brodée en cm', heightHint: 'surface brodée en cm', densityHint: 'points par cm', coloursHint: 'la première couleur ne demande pas de changement', speedHint: 'points par minute', rateHint: 'votre monnaie par heure', stitchRunning: 'Point courant', stitchSatin: 'Point satin', stitchFill: 'Point de remplissage', stitchTatami: 'Remplissage tatami', stitchRunningNote: 'Contours légers et lettrage avec une couverture réduite.', stitchSatinNote: 'Colonnes et bordures lisses avec un trajet de fil concentré.', stitchFillNote: 'Couverture pleine qui ajoute du fil et du temps de production.', stitchTatamiNote: 'Remplissage en couches avec le facteur de planification le plus élevé.', selectStitch: 'Choisir un type de point', emptyResult: 'Saisissez un plan pour activer le cadre.', stitchesUnit: 'points équivalents', minutesUnit: 'minutes', hoursUnit: 'heures', priceUnit: 'unités monétaires', areaLabel: 'Surface brodée', effectiveLabel: 'Points équivalents', stitchTimeLabel: 'Temps de broderie', productionLabel: 'Temps de production', setupLabel: 'Préparation des couleurs', changesLabel: 'Changements de couleur', basePriceLabel: 'Coût de main-d\'oeuvre', estimateBadge: 'Estimation prête', attentionBadge: 'Vérifier l\'échelle', warningHighVolume: 'Grand volume de points. Faites un essai machine avant de préparer un devis.', warningLongRun: 'Longue production. Vérifiez séparément le cadrage, les casses de fil et la finition.', invalidMessage: 'Utilisez des valeurs positives pour la taille, la densité, la vitesse et le tarif horaire.', formulaTitle: 'Ce qui est compté', formulaText: 'La surface multipliée par la densité au carré donne la base de couverture. Le facteur de point la transforme en points équivalents, puis chaque changement après la première couleur ajoute 1,75 minute.', noteTitle: 'Limite de planification', noteText: 'Cet outil est un estimateur transparent, pas un fichier machine numérisé ni un devis final. Ajoutez vous-même les matières, la préparation, la finition, les frais, les taxes et la marge.', reset: 'Réinitialiser l\'exemple', copied: 'Résumé copié', copySummary: 'Copier le résumé', canvasAlt: 'Cadre de broderie en tissu avec des lignes de fil montrant la densité actuelle',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Estimer les points et le prix de main-d\'oeuvre en broderie', level: 2 },
  { type: 'paragraph', html: 'Un motif de broderie pose deux questions de planification: quelle quantité de travail de fil contient-il et combien de temps la machine et son opérateur seront-ils occupés ? Cet estimateur garde ces deux sujets visibles et transforme la taille, la densité, le point, les couleurs, la vitesse et le tarif en une valeur comparable.' },
  { type: 'title', text: 'Le modèle de points', level: 3 },
  { type: 'paragraph', html: 'La base est la surface brodée multipliée par le carré de la densité en points par centimètre. Un facteur relatif tient compte de la famille de points: le point courant est plus léger, le satin sert de référence et les remplissages sont des cas de planification plus denses. Il s\'agit d\'une estimation du travail équivalent, pas du nombre exact exporté par un logiciel de numérisation.' },
  { type: 'table', headers: ['Entrée', 'Ce qui change', 'Ce qui n\'est pas promis'], rows: [['Largeur et hauteur', 'Surface couverte et base de points', 'Le contour exact du fichier numérisé'], ['Densité et type de point', 'Travail de fil équivalent et temps machine', 'Un réglage de qualité universel pour chaque tissu'], ['Couleurs', 'Temps de changement après la première couleur', 'Le nombre de coupes ou de casses de fil'], ['Vitesse et tarif', 'Durée de production et valeur de main-d\'oeuvre', 'Un devis final pour le client']] },
  { type: 'title', text: 'Transformer une estimation en prix responsable', level: 3 },
  { type: 'paragraph', html: 'Le prix affiché correspond seulement au temps de travail multiplié par le tarif horaire. Un devis réel doit ajouter la numérisation, le fil, le stabilisateur, le cadrage, la préparation, les essais, les coupes, les reprises, la finition, les frais, les taxes et la marge. Gardez ces éléments explicites afin qu\'un petit nombre de points ne cache pas une préparation longue.' },
  { type: 'tip', title: 'Tester le plan avant le devis', html: 'Réalisez un échantillon représentatif sur le tissu et le stabilisateur prévus. Comparez son temps et le comportement du fil avec l\'estimation, puis ajustez vos hypothèses locales de vitesse et de préparation.' },
  { type: 'title', text: 'Lire le détail de production', level: 3 },
  { type: 'list', items: ['Les points équivalents montrent la charge de couverture après application du facteur.', 'Le temps de production correspond aux points équivalents divisés par la vitesse machine.', 'La préparation des couleurs ajoute 1,75 minute pour chaque changement après le premier.', 'Le coût de base est le temps total divisé par 60 puis multiplié par le tarif horaire.'] },
] };
