import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'kalkulator-jumlah-tusuk-harga-bordir';
const title = 'Kalkulator jumlah tusuk dan harga bordir';
const description = 'Perkirakan jumlah tusuk, waktu produksi, dan biaya tenaga kerja dasar dari ukuran desain, kepadatan tusuk, warna, kecepatan, dan tarif per jam.';
const faq = [
  { question: 'Bagaimana cara kerja perkiraan jumlah tusuk?', answer: 'Kalkulator mengalikan luas bordir dengan kuadrat kepadatan tusuk, lalu menerapkan faktor jenis tusuk. Hasilnya adalah beban kerja setara untuk membandingkan produksi, bukan prediksi file mesin.' },
  { question: 'Mengapa jenis tusuk mengubah perkiraan?', answer: 'Tusuk lari, satin, isi, dan tatami menempatkan benang dengan cara berbeda. Faktor relatif yang transparan menunjukkan bahwa cakupan lebih padat memerlukan usaha produksi lebih besar.' },
  { question: 'Apakah jumlah warna mengubah jumlah tusuk?', answer: 'Tidak. Jumlah warna hanya menambah waktu pergantian. Model ini menghitung 1,75 menit untuk setiap pergantian setelah warna pertama sebagai asumsi perencanaan.' },
  { question: 'Apakah harga yang dihitung merupakan penawaran?', answer: 'Bukan. Ini adalah perkiraan tenaga kerja berdasarkan tarif per jam yang dimasukkan. Benang, stabilizer, digitalisasi, persiapan, penyelesaian, biaya operasional, pajak, dan keuntungan belum termasuk.' },
];
const howTo = [
  { name: 'Ukur desain', text: 'Masukkan lebar dan tinggi bordir dalam sentimeter. Gunakan area yang benar-benar diberi tusuk, bukan ukuran bingkai seluruhnya.' },
  { name: 'Jelaskan rencana tusuk', text: 'Pilih jenis tusuk utama, masukkan kepadatan dalam tusuk per sentimeter, lalu hitung warna benang.' },
  { name: 'Masukkan asumsi produksi', text: 'Masukkan kecepatan mesin dalam tusuk per menit dan tarif tenaga kerja per jam. Gunakan satu mata uang yang konsisten.' },
  { name: 'Baca perkiraan perencanaan', text: 'Gunakan tusuk setara, waktu produksi, waktu persiapan, dan biaya dasar untuk membandingkan desain sebelum digitalisasi atau penawaran.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'id' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Susun rencana tusuk di bingkai bordir, lalu lihat usaha produksi dan nilai tenaga kerjanya.', stageLabel: 'Bingkai tusuk', controlsLabel: 'Buat rencana tusuk', resultLabel: 'Perkiraan tenaga kerja dasar', widthLabel: 'Lebar desain', heightLabel: 'Tinggi desain', densityLabel: 'Kepadatan tusuk', stitchLabel: 'Jenis tusuk utama', coloursLabel: 'Warna benang', speedLabel: 'Kecepatan mesin', rateLabel: 'Tarif per jam', widthHint: 'area bordir dalam cm', heightHint: 'area bordir dalam cm', densityHint: 'tusuk per cm', coloursHint: 'warna pertama tidak perlu pergantian', speedHint: 'tusuk per menit', rateHint: 'mata uang per jam', stitchRunning: 'Tusuk lari', stitchSatin: 'Tusuk satin', stitchFill: 'Tusuk isi', stitchTatami: 'Isi tatami', stitchRunningNote: 'Garis ringan dan tulisan dengan cakupan rendah.', stitchSatinNote: 'Kolom dan batas halus dengan jalur benang terarah.', stitchFillNote: 'Cakupan penuh yang menambah benang dan usaha produksi.', stitchTatamiNote: 'Isi berlapis dengan faktor perencanaan tertinggi.', selectStitch: 'Pilih jenis tusuk', emptyResult: 'Masukkan rencana tusuk untuk mengaktifkan bingkai.', stitchesUnit: 'tusuk setara', minutesUnit: 'menit', hoursUnit: 'jam', priceUnit: 'satuan mata uang', areaLabel: 'Luas bordir', effectiveLabel: 'Tusuk setara', stitchTimeLabel: 'Waktu menyulam', productionLabel: 'Waktu produksi', setupLabel: 'Persiapan warna', changesLabel: 'Pergantian warna', basePriceLabel: 'Perkiraan tenaga kerja dasar', estimateBadge: 'Perkiraan siap', attentionBadge: 'Periksa skala', warningHighVolume: 'Jumlah tusuk besar. Lakukan sampel mesin nyata sebelum membuat penawaran.', warningLongRun: 'Proses produksi panjang. Periksa pembingkaian, putus benang, dan penyelesaian secara terpisah.', invalidMessage: 'Gunakan nilai positif untuk ukuran, kepadatan, kecepatan, dan tarif per jam.', formulaTitle: 'Yang dihitung', formulaText: 'Luas dikali kepadatan kuadrat menghasilkan dasar cakupan. Faktor tusuk mengubahnya menjadi tusuk setara, sedangkan setiap pergantian setelah warna pertama menambah 1,75 menit.', noteTitle: 'Batas perencanaan', noteText: 'Ini adalah kalkulator transparan, bukan file mesin yang sudah didigitalisasi atau penawaran akhir. Tambahkan bahan, persiapan, penyelesaian, biaya, pajak, dan margin sendiri.', reset: 'Atur ulang contoh', copied: 'Ringkasan disalin', copySummary: 'Salin ringkasan', canvasAlt: 'Bingkai bordir kain dengan garis benang yang menunjukkan kepadatan saat ini',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Cara memperkirakan jumlah tusuk dan harga tenaga kerja bordir', level: 2 },
  { type: 'paragraph', html: 'Desain bordir memiliki dua pertanyaan perencanaan: seberapa banyak pekerjaan benang dalam motif dan berapa lama mesin serta operator akan digunakan. Kalkulator ini menampilkan keduanya dan mengubah ukuran, kepadatan, jenis tusuk, warna, kecepatan, serta tarif menjadi angka perencanaan yang dapat dibandingkan.' },
  { type: 'title', text: 'Model jumlah tusuk', level: 3 },
  { type: 'paragraph', html: 'Dasarnya adalah luas bordir dikalikan kuadrat kepadatan dalam tusuk per sentimeter. Faktor relatif kemudian memperhitungkan keluarga tusuk: tusuk lari lebih ringan, satin menjadi acuan, sedangkan isi dan tatami adalah kasus perencanaan yang makin padat. Ini adalah perkiraan pekerjaan setara, bukan jumlah tepat yang diekspor perangkat lunak digitalisasi.' },
  { type: 'table', headers: ['Masukan', 'Yang berubah', 'Yang tidak dijanjikan'], rows: [['Lebar dan tinggi', 'Luas cakupan dan jumlah tusuk dasar', 'Garis luar tepat dari file digitalisasi'], ['Kepadatan dan jenis tusuk', 'Pekerjaan benang setara dan waktu mesin', 'Pengaturan kualitas universal untuk semua kain'], ['Warna', 'Waktu pergantian setelah warna pertama', 'Jumlah potongan atau putus benang'], ['Kecepatan dan tarif', 'Durasi produksi dan nilai tenaga kerja', 'Penawaran akhir kepada pelanggan']] },
  { type: 'title', text: 'Mengubah perkiraan menjadi harga yang bertanggung jawab', level: 3 },
  { type: 'paragraph', html: 'Harga yang ditampilkan hanya menghitung waktu kerja dikali tarif per jam. Penawaran nyata harus menambahkan digitalisasi, benang, stabilizer, pembingkaian, persiapan mesin, sampel, pemotongan, pengerjaan ulang, penyelesaian, biaya operasional, pajak, dan margin. Pisahkan semua tambahan agar jumlah tusuk kecil tidak menyembunyikan persiapan yang lama.' },
  { type: 'tip', title: 'Uji rencana sebelum membuat penawaran', html: 'Jalankan sampel yang mewakili pada kain dan stabilizer yang akan digunakan. Bandingkan waktunya serta perilaku benang dengan perkiraan, lalu sesuaikan asumsi kecepatan dan persiapan lokal.' },
  { type: 'title', text: 'Membaca rincian produksi', level: 3 },
  { type: 'list', items: ['Tusuk setara menunjukkan beban cakupan setelah faktor tusuk diterapkan.', 'Waktu produksi adalah tusuk setara dibagi kecepatan mesin.', 'Persiapan warna menambah 1,75 menit untuk setiap pergantian setelah yang pertama.', 'Perkiraan tenaga kerja dasar adalah total waktu dibagi 60 lalu dikali tarif per jam.'] },
] };
