import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'calcolatore-punti-prezzo-ricamo';
const title = 'Calcolatore dei punti e del prezzo del ricamo';
const description = 'Stima punti, tempi di produzione e costo base della manodopera in base a dimensioni, densità, colori, velocità e tariffa oraria.';
const faq = [
  { question: 'Come funziona la stima del numero di punti?', answer: 'Il calcolatore moltiplica la superficie ricamata per il quadrato della densità dei punti e applica poi un fattore per il tipo di punto. Il risultato confronta il lavoro di produzione, ma non predice il file della macchina.' },
  { question: 'Perché il tipo di punto cambia la stima?', answer: 'Punto filza, satin, riempimento e tatami depositano il filo in modo diverso. Il fattore relativo mostra con chiarezza che una copertura più densa richiede più lavoro.' },
  { question: 'Il numero di colori cambia il numero di punti?', answer: 'No. I colori aggiungono solo il tempo di cambio. Il modello considera 1,75 minuti per ogni cambio dopo il primo colore come ipotesi di pianificazione.' },
  { question: 'Il prezzo calcolato è un preventivo?', answer: 'No. È una stima della manodopera basata sulla tariffa oraria inserita. Filo, stabilizzatore, digitalizzazione, preparazione, finitura, costi generali, tasse e margine non sono inclusi.' },
];
const howTo = [
  { name: 'Misura il disegno', text: 'Inserisci larghezza e altezza ricamate in centimetri. Usa la superficie cucita, non la dimensione completa del telaio.' },
  { name: 'Descrivi il piano punti', text: 'Scegli il tipo dominante, inserisci la densità in punti per centimetro e conta i colori del filo.' },
  { name: 'Aggiungi le ipotesi', text: 'Inserisci la velocità in punti al minuto e la tariffa di manodopera oraria. Mantieni una sola valuta.' },
  { name: 'Leggi la stima', text: 'Usa punti equivalenti, tempo di produzione, preparazione e costo base per confrontare i disegni prima della digitalizzazione o del preventivo.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'it' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Componi il tuo piano punti nel telaio e scopri l\'impegno di produzione e il suo valore di manodopera.', stageLabel: 'Il telaio da ricamo', controlsLabel: 'Crea il piano punti', resultLabel: 'Costo base della manodopera', widthLabel: 'Larghezza del disegno', heightLabel: 'Altezza del disegno', densityLabel: 'Densità dei punti', stitchLabel: 'Punto dominante', coloursLabel: 'Colori del filo', speedLabel: 'Velocità macchina', rateLabel: 'Tariffa oraria', widthHint: 'superficie ricamata in cm', heightHint: 'superficie ricamata in cm', densityHint: 'punti per cm', coloursHint: 'il primo colore non richiede un cambio', speedHint: 'punti al minuto', rateHint: 'la tua valuta all\'ora', stitchRunning: 'Punto filza', stitchSatin: 'Punto satin', stitchFill: 'Punto di riempimento', stitchTatami: 'Riempimento tatami', stitchRunningNote: 'Contorni leggeri e lettere con copertura ridotta.', stitchSatinNote: 'Colonne e bordi lisci con un percorso del filo concentrato.', stitchFillNote: 'Copertura piena che aggiunge filo e tempo di produzione.', stitchTatamiNote: 'Riempimento a strati con il fattore di pianificazione più alto.', selectStitch: 'Scegli un tipo di punto', emptyResult: 'Inserisci un piano per attivare il telaio.', stitchesUnit: 'punti equivalenti', minutesUnit: 'minuti', hoursUnit: 'ore', priceUnit: 'unità monetarie', areaLabel: 'Superficie ricamata', effectiveLabel: 'Punti equivalenti', stitchTimeLabel: 'Tempo di ricamo', productionLabel: 'Tempo di produzione', setupLabel: 'Preparazione colori', changesLabel: 'Cambi colore', basePriceLabel: 'Costo base della manodopera', estimateBadge: 'Stima pronta', attentionBadge: 'Controlla la scala', warningHighVolume: 'Grande volume di punti. Fai una prova reale prima del preventivo.', warningLongRun: 'Produzione lunga. Controlla separatamente il telaio, le rotture del filo e la finitura.', invalidMessage: 'Usa valori positivi per dimensioni, densità, velocità e tariffa oraria.', formulaTitle: 'Cosa viene contato', formulaText: 'La superficie moltiplicata per la densità al quadrato crea la base di copertura. Il fattore del punto la trasforma in punti equivalenti; ogni cambio dopo il primo colore aggiunge 1,75 minuti.', noteTitle: 'Limite della pianificazione', noteText: 'È un calcolatore trasparente, non un file macchina digitalizzato né un preventivo finale. Aggiungi materiali, preparazione, finitura, costi, tasse e margine.', reset: 'Ripristina esempio', copied: 'Riepilogo copiato', copySummary: 'Copia riepilogo', canvasAlt: 'Telaio da ricamo in tessuto con linee di filo che mostrano la densità attuale',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Come stimare punti e prezzo della manodopera di ricamo', level: 2 },
  { type: 'paragraph', html: 'Un disegno da ricamo pone due domande di pianificazione: quanto lavoro di filo contiene il motivo e per quanto tempo la macchina e l\'operatore saranno impegnati? Questo strumento mantiene visibili entrambe e trasforma dimensioni, densità, punto, colori, velocità e tariffa in un valore confrontabile.' },
  { type: 'title', text: 'Il modello dei punti', level: 3 },
  { type: 'paragraph', html: 'La base è la superficie ricamata moltiplicata per il quadrato della densità in punti per centimetro. Un fattore relativo considera la famiglia di punti: il punto filza è più leggero, il satin è il riferimento e i riempimenti sono casi di pianificazione progressivamente più densi. È una stima del lavoro equivalente, non il conteggio esatto esportato da un software di digitalizzazione.' },
  { type: 'table', headers: ['Input', 'Cosa cambia', 'Cosa non promette'], rows: [['Larghezza e altezza', 'Superficie coperta e punti di base', 'Il contorno esatto di un file digitalizzato'], ['Densità e tipo di punto', 'Lavoro equivalente e tempo macchina', 'Un\'impostazione di qualità universale per ogni tessuto'], ['Colori', 'Tempo di cambio dopo il primo colore', 'Il numero di tagli o rotture del filo'], ['Velocità e tariffa', 'Durata di produzione e valore del lavoro', 'Un preventivo finale per il cliente']] },
  { type: 'title', text: 'Trasformare una stima in un prezzo responsabile', level: 3 },
  { type: 'paragraph', html: 'Il prezzo mostrato moltiplica soltanto il tempo di lavoro per la tariffa oraria. Un preventivo reale deve aggiungere digitalizzazione, filo, stabilizzatore, intelaiatura, preparazione, campioni, tagli, rilavorazioni, finitura, costi generali, tasse e margine. Mantieni queste voci separate, così un basso numero di punti non nasconde una preparazione laboriosa.' },
  { type: 'tip', title: 'Prova il piano prima del preventivo', html: 'Esegui un campione rappresentativo sul tessuto e sullo stabilizzatore previsti. Confronta tempo e comportamento del filo con la stima e regola le ipotesi locali di velocità e preparazione.' },
  { type: 'title', text: 'Leggere il dettaglio della produzione', level: 3 },
  { type: 'list', items: ['I punti equivalenti mostrano il carico di copertura dopo l\'applicazione del fattore.', 'Il tempo di produzione è dato dai punti equivalenti divisi per la velocità della macchina.', 'La preparazione dei colori aggiunge 1,75 minuti per ogni cambio dopo il primo.', 'Il costo base è il tempo totale diviso per 60 e moltiplicato per la tariffa oraria.'] },
] };
