import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'schatting-steekenaantal-prijs-borduren';
const title = 'Schatting van steken en borduurprijs';
const description = 'Schat het aantal borduursteken, de productietijd en een basisprijs voor arbeid op basis van formaat, steekdichtheid, kleuren, snelheid en uurtarief.';
const faq = [
  { question: 'Hoe werkt de schatting van het aantal steken?', answer: 'De calculator vermenigvuldigt het geborduurde oppervlak met het kwadraat van de steekdichtheid en past daarna een factor voor het steektype toe. Zo ontstaat een vergelijkbare werklast, geen voorspelling van een machinebestand.' },
  { question: 'Waarom verandert het steektype de schatting?', answer: 'Doorlopende steek, satijn, vulsteek en tatami leggen draad op verschillende manieren. De transparante relatieve factor laat zien dat een dichtere bedekking meer productiewerk vraagt.' },
  { question: 'Verandert het aantal kleuren het aantal steken?', answer: 'Nee. Het aantal kleuren voegt alleen wisseltijd toe. Het model rekent 1,75 minuut voor elke wissel na de eerste kleur als planningsaanname.' },
  { question: 'Is de berekende prijs een offerte?', answer: 'Nee. Het is een schatting van arbeid op basis van het ingevoerde uurtarief. Draad, versteviging, digitaliseren, instellen, afwerking, overhead, belasting en winstmarge zijn niet inbegrepen.' },
];
const howTo = [
  { name: 'Meet het ontwerp', text: 'Voer de geborduurde breedte en hoogte in centimeters in. Gebruik het gestikte oppervlak en niet de volledige borduurring.' },
  { name: 'Beschrijf het steekplan', text: 'Kies het dominante steektype, voer de dichtheid in steken per centimeter in en tel de draadkleuren.' },
  { name: 'Voeg productieaannames toe', text: 'Voer de machinesnelheid in steken per minuut en je arbeidsloon per uur in. Gebruik steeds dezelfde munteenheid.' },
  { name: 'Lees de planningsschatting', text: 'Gebruik equivalente steken, productietijd, insteltijd en basisprijs om ontwerpen te vergelijken voor je gaat digitaliseren of offreren.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'nl' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Bouw je steekplan in de borduurring en bekijk de productiewerklast en arbeidswaarde.', stageLabel: 'De borduurring', controlsLabel: 'Bouw het steekplan', resultLabel: 'Basisprijs voor arbeid', widthLabel: 'Breedte van het ontwerp', heightLabel: 'Hoogte van het ontwerp', densityLabel: 'Steekdichtheid', stitchLabel: 'Dominant steektype', coloursLabel: 'Draadkleuren', speedLabel: 'Machinesnelheid', rateLabel: 'Uurtarief', widthHint: 'gestikt oppervlak in cm', heightHint: 'gestikt oppervlak in cm', densityHint: 'steken per cm', coloursHint: 'de eerste kleur heeft geen wissel nodig', speedHint: 'steken per minuut', rateHint: 'jouw valuta per uur', stitchRunning: 'Doorlopende steek', stitchSatin: 'Satijnsteek', stitchFill: 'Vulsteek', stitchTatami: 'Tatamivulling', stitchRunningNote: 'Lichte contouren en letters met weinig bedekking.', stitchSatinNote: 'Gladde kolommen en randen met een gericht draadpad.', stitchFillNote: 'Volledige bedekking die draad en productiewerk toevoegt.', stitchTatamiNote: 'Gelaagde vulling met de hoogste planningsfactor in dit model.', selectStitch: 'Kies een steektype', emptyResult: 'Voer een steekplan in om de ring te activeren.', stitchesUnit: 'equivalente steken', minutesUnit: 'minuten', hoursUnit: 'uur', priceUnit: 'valuta-eenheden', areaLabel: 'Geborduurd oppervlak', effectiveLabel: 'Equivalente steken', stitchTimeLabel: 'Steektijd', productionLabel: 'Productietijd', setupLabel: 'Kleurinstelling', changesLabel: 'Kleurwissels', basePriceLabel: 'Basisprijs voor arbeid', estimateBadge: 'Schatting klaar', attentionBadge: 'Schaal controleren', warningHighVolume: 'Groot aantal steken. Maak een echte machineproef voordat je een offerte maakt.', warningLongRun: 'Lange productierun. Controleer het opspannen, draadbreuken en afwerking apart.', invalidMessage: 'Gebruik positieve waarden voor formaat, dichtheid, snelheid en uurtarief.', formulaTitle: 'Wat wordt geteld', formulaText: 'Oppervlak maal dichtheid in het kwadraat geeft de basis voor bedekking. De steekfactor maakt er equivalente steken van en elke wissel na de eerste kleur voegt 1,75 minuut toe.', noteTitle: 'Planningsgrens', noteText: 'Dit is een transparante schatting, geen gedigitaliseerd machinebestand of definitieve offerte. Voeg materiaal, instelling, afwerking, overhead, belasting en marge zelf toe.', reset: 'Voorbeeld resetten', copied: 'Samenvatting gekopieerd', copySummary: 'Samenvatting kopiëren', canvasAlt: 'Borduurring van stof met draadlijnen die de huidige dichtheid tonen',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Zo schat je steken en arbeidsprijs voor borduurwerk', level: 2 },
  { type: 'paragraph', html: 'Een borduurontwerp stelt twee planningsvragen: hoeveel draadwerk zit er in het motief en hoe lang zijn machine en bediener bezig? Deze calculator houdt beide zichtbaar en zet formaat, dichtheid, steektype, kleuren, snelheid en tarief om in een vergelijkbare planningswaarde.' },
  { type: 'title', text: 'Het model voor steekenaantal', level: 3 },
  { type: 'paragraph', html: 'De basis is het geborduurde oppervlak maal het kwadraat van de dichtheid in steken per centimeter. Een relatieve factor houdt rekening met de steekfamilie: doorlopende steek is lichter, satijn is het ijkpunt en vulling en tatami zijn steeds dichtere planningsgevallen. Dit is een schatting van equivalent werk, niet het exacte aantal uit digitaliseersoftware.' },
  { type: 'table', headers: ['Invoer', 'Wat het verandert', 'Wat het niet belooft'], rows: [['Breedte en hoogte', 'Bedekkingsoppervlak en basissteken', 'De exacte omtrek van een gedigitaliseerd bestand'], ['Dichtheid en steektype', 'Equivalente draadwerklast en machinetijd', 'Een universele kwaliteitsinstelling voor elke stof'], ['Kleuren', 'Wisseltijd na de eerste kleur', 'Het aantal draadknippen of draadbreuken'], ['Snelheid en tarief', 'Productieduur en arbeidswaarde', 'Een definitieve klantofferte']] },
  { type: 'title', text: 'Maak van een schatting een verantwoorde prijs', level: 3 },
  { type: 'paragraph', html: 'De getoonde prijs is alleen werktijd maal je uurtarief. Een echte offerte moet digitaliseren, draad, versteviging, opspannen, machine-instelling, proefstukken, knippen, herstelwerk, afwerking, overhead, belasting en marge toevoegen. Houd deze posten zichtbaar zodat een laag steekenaantal geen lange voorbereiding verbergt.' },
  { type: 'tip', title: 'Test het plan voor je offert', html: 'Maak een representatief proefstuk op de bedoelde stof en versteviging. Vergelijk tijd en draadgedrag met de schatting en pas je lokale aannames voor snelheid en instelling aan.' },
  { type: 'title', text: 'De productieverdeling lezen', level: 3 },
  { type: 'list', items: ['Equivalente steken tonen de bedekkingswerklast na toepassing van de steekfactor.', 'Productietijd is het aantal equivalente steken gedeeld door de machinesnelheid.', 'Kleurinstelling voegt 1,75 minuut toe voor elke wissel na de eerste kleur.', 'De basisprijs is de totale tijd gedeeld door 60 en vermenigvuldigd met het uurtarief.'] },
] };
