import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'kalkulator-liczby-sciegow-ceny-haftu';
const title = 'Kalkulator liczby ściegów i ceny haftu';
const description = 'Oszacuj liczbę ściegów, czas produkcji i podstawowy koszt pracy na podstawie rozmiaru wzoru, gęstości, kolorów, prędkości i stawki godzinowej.';
const faq = [
  { question: 'Jak działa szacowanie liczby ściegów?', answer: 'Kalkulator mnoży wyhaftowaną powierzchnię przez kwadrat gęstości ściegów, a następnie stosuje współczynnik rodzaju ściegu. Powstaje porównywalne obciążenie pracy, a nie prognoza pliku maszyny.' },
  { question: 'Dlaczego rodzaj ściegu zmienia wynik?', answer: 'Ścieg bieżący, satynowy, wypełniający i tatami układają nić w różny sposób. Przejrzysty współczynnik pokazuje, że gęstsze pokrycie wymaga większego nakładu produkcyjnego.' },
  { question: 'Czy liczba kolorów zmienia liczbę ściegów?', answer: 'Nie. Liczba kolorów dodaje tylko czas przezbrojenia. Model przyjmuje 1,75 minuty za każdą zmianę po pierwszym kolorze jako założenie planistyczne.' },
  { question: 'Czy obliczona cena jest wyceną?', answer: 'Nie. To szacunek pracy oparty na wpisanej stawce godzinowej. Nici, stabilizator, digitalizacja, przygotowanie, wykończenie, koszty stałe, podatki i marża nie są uwzględnione.' },
];
const howTo = [
  { name: 'Zmierz wzór', text: 'Wpisz wyhaftowaną szerokość i wysokość w centymetrach. Użyj obszaru z haftem, a nie całego rozmiaru tamborka.' },
  { name: 'Opisz plan ściegów', text: 'Wybierz dominujący rodzaj ściegu, wpisz gęstość w ściegach na centymetr i policz kolory nici.' },
  { name: 'Dodaj założenia produkcyjne', text: 'Wpisz prędkość maszyny w ściegach na minutę i stawkę pracy za godzinę. Zachowaj jedną walutę.' },
  { name: 'Odczytaj szacunek', text: 'Użyj ściegów równoważnych, czasu produkcji, czasu przygotowania i ceny bazowej do porównania wzorów.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'pl' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Zbuduj plan ściegów w tamborku i zobacz nakład produkcyjny oraz wartość pracy.', stageLabel: 'Tamborek haftu', controlsLabel: 'Zbuduj plan ściegów', resultLabel: 'Podstawowy koszt pracy', widthLabel: 'Szerokość wzoru', heightLabel: 'Wysokość wzoru', densityLabel: 'Gęstość ściegów', stitchLabel: 'Dominujący rodzaj ściegu', coloursLabel: 'Kolory nici', speedLabel: 'Prędkość maszyny', rateLabel: 'Stawka godzinowa', widthHint: 'obszar haftu w cm', heightHint: 'obszar haftu w cm', densityHint: 'ściegi na cm', coloursHint: 'pierwszy kolor nie wymaga zmiany', speedHint: 'ściegi na minutę', rateHint: 'twoja waluta za godzinę', stitchRunning: 'Ścieg bieżący', stitchSatin: 'Ścieg satynowy', stitchFill: 'Ścieg wypełniający', stitchTatami: 'Wypełnienie tatami', stitchRunningNote: 'Lekkie kontury i napisy z małym pokryciem.', stitchSatinNote: 'Gładkie kolumny i krawędzie ze skupioną ścieżką nici.', stitchFillNote: 'Pełne pokrycie, które zwiększa zużycie nici i nakład pracy.', stitchTatamiNote: 'Warstwowe wypełnienie z najwyższym współczynnikiem planowania.', selectStitch: 'Wybierz rodzaj ściegu', emptyResult: 'Wpisz plan ściegów, aby uruchomić tamborek.', stitchesUnit: 'ściegi równoważne', minutesUnit: 'minuty', hoursUnit: 'godziny', priceUnit: 'jednostki waluty', areaLabel: 'Wyhaftowana powierzchnia', effectiveLabel: 'Ściegi równoważne', stitchTimeLabel: 'Czas haftowania', productionLabel: 'Czas produkcji', setupLabel: 'Przygotowanie kolorów', changesLabel: 'Zmiany kolorów', basePriceLabel: 'Podstawowy koszt pracy', estimateBadge: 'Szacunek gotowy', attentionBadge: 'Sprawdź skalę', warningHighVolume: 'Duża liczba ściegów. Wykonaj próbę na maszynie przed wyceną.', warningLongRun: 'Długi cykl produkcyjny. Osobno sprawdź tamborek, zerwania nici i wykończenie.', invalidMessage: 'Użyj dodatnich wartości rozmiaru, gęstości, prędkości i stawki godzinowej.', formulaTitle: 'Co jest liczone', formulaText: 'Powierzchnia razy gęstość do kwadratu daje podstawę pokrycia. Współczynnik ściegu zamienia ją na ściegi równoważne, a każda zmiana po pierwszym kolorze dodaje 1,75 minuty.', noteTitle: 'Granica planowania', noteText: 'To przejrzysty kalkulator, a nie zdigitalizowany plik maszyny ani końcowa wycena. Samodzielnie dodaj materiały, przygotowanie, wykończenie, koszty, podatki i marżę.', reset: 'Zresetuj przykład', copied: 'Skopiowano podsumowanie', copySummary: 'Kopiuj podsumowanie', canvasAlt: 'Tamborek z tkaniną i liniami nici pokazującymi obecną gęstość',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Jak oszacować liczbę ściegów i koszt pracy przy hafcie', level: 2 },
  { type: 'paragraph', html: 'Wzór haftu stawia dwa pytania planistyczne: ile pracy nici zawiera motyw i jak długo maszyna oraz operator będą zajęci? Ten kalkulator pokazuje oba aspekty i zamienia rozmiar, gęstość, rodzaj ściegu, kolory, prędkość oraz stawkę w porównywalną wartość planistyczną.' },
  { type: 'title', text: 'Model liczby ściegów', level: 3 },
  { type: 'paragraph', html: 'Podstawa to wyhaftowana powierzchnia pomnożona przez kwadrat gęstości w ściegach na centymetr. Współczynnik względny uwzględnia rodzinę ściegów: ścieg bieżący jest lżejszy, satyna stanowi punkt odniesienia, a wypełnienie i tatami są coraz gęstszymi przypadkami planistycznymi. To szacunek pracy równoważnej, a nie dokładna liczba eksportowana przez program do digitalizacji.' },
  { type: 'table', headers: ['Dane', 'Co zmieniają', 'Czego nie obiecują'], rows: [['Szerokość i wysokość', 'Powierzchnię pokrycia i liczbę bazową', 'Dokładnego obrysu zdigitalizowanego pliku'], ['Gęstość i rodzaj ściegu', 'Równoważną pracę nici i czas maszyny', 'Uniwersalnego ustawienia jakości dla każdej tkaniny'], ['Kolory', 'Czas zmiany po pierwszym kolorze', 'Liczby obcięć ani zerwań nici'], ['Prędkość i stawka', 'Czas produkcji i wartość pracy', 'Końcowej wyceny dla klienta']] },
  { type: 'title', text: 'Zamień szacunek w odpowiedzialną cenę', level: 3 },
  { type: 'paragraph', html: 'Pokazana cena to tylko czas pracy pomnożony przez stawkę godzinową. Prawdziwa wycena powinna dodać digitalizację, nici, stabilizator, mocowanie, ustawienie maszyny, próbki, obcinanie, poprawki, wykończenie, koszty stałe, podatki i marżę. Rozdziel te elementy, aby mała liczba ściegów nie ukryła pracochłonnego przygotowania.' },
  { type: 'tip', title: 'Przetestuj plan przed wyceną', html: 'Wykonaj reprezentatywną próbę na docelowej tkaninie i stabilizatorze. Porównaj czas oraz zachowanie nici z szacunkiem, a potem dopasuj lokalne założenia prędkości i przygotowania.' },
  { type: 'title', text: 'Jak czytać podział produkcji', level: 3 },
  { type: 'list', items: ['Ściegi równoważne pokazują obciążenie pokrycia po zastosowaniu współczynnika.', 'Czas produkcji to ściegi równoważne podzielone przez prędkość maszyny.', 'Przygotowanie kolorów dodaje 1,75 minuty za każdą zmianę po pierwszej.', 'Podstawowy koszt pracy to łączny czas podzielony przez 60 i pomnożony przez stawkę godzinową.'] },
] };
