import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'calculadora-pontos-preco-bordado';
const title = 'Calculadora de pontos e preço de bordado';
const description = 'Estime pontos, tempo de produção e custo base de mão de obra com base no tamanho, densidade, cores, velocidade e valor por hora.';
const faq = [
  { question: 'Como funciona a estimativa de pontos?', answer: 'A calculadora multiplica a área bordada pelo quadrado da densidade de pontos e aplica um fator conforme o tipo de ponto. O resultado é uma carga de trabalho equivalente para comparar produções, não uma previsão do arquivo da máquina.' },
  { question: 'Por que o tipo de ponto muda a estimativa?', answer: 'Ponto corrido, cetim, preenchimento e tatami depositam a linha de maneiras diferentes. O fator relativo mostra com transparência que uma cobertura mais densa exige mais trabalho de produção.' },
  { question: 'A quantidade de cores muda o número de pontos?', answer: 'Não. As cores acrescentam apenas tempo de troca. O modelo considera 1,75 minuto para cada troca depois da primeira cor como uma hipótese de planejamento.' },
  { question: 'O preço calculado é um orçamento?', answer: 'Não. É uma estimativa de mão de obra usando o valor por hora informado. Linha, estabilizador, digitalização, preparação, acabamento, despesas, impostos e margem de lucro não estão incluídos.' },
];
const howTo = [
  { name: 'Meça o desenho', text: 'Informe a largura e a altura bordadas em centímetros. Use a área que receberá pontos, não o tamanho total do bastidor.' },
  { name: 'Descreva o plano de pontos', text: 'Escolha o tipo dominante, informe a densidade em pontos por centímetro e conte as cores da linha.' },
  { name: 'Adicione as hipóteses', text: 'Informe a velocidade em pontos por minuto e o valor da mão de obra por hora. Mantenha uma única moeda.' },
  { name: 'Leia a estimativa', text: 'Use pontos equivalentes, tempo de produção, preparação e custo base para comparar desenhos antes da digitalização ou do orçamento.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'pt' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Monte seu plano de pontos no bastidor e veja o esforço de produção e o valor da mão de obra.', stageLabel: 'O bastidor de pontos', controlsLabel: 'Monte o plano de pontos', resultLabel: 'Estimativa base de mão de obra', widthLabel: 'Largura do desenho', heightLabel: 'Altura do desenho', densityLabel: 'Densidade de pontos', stitchLabel: 'Ponto dominante', coloursLabel: 'Cores da linha', speedLabel: 'Velocidade da máquina', rateLabel: 'Valor por hora', widthHint: 'área bordada em cm', heightHint: 'área bordada em cm', densityHint: 'pontos por cm', coloursHint: 'a primeira cor não exige troca', speedHint: 'pontos por minuto', rateHint: 'sua moeda por hora', stitchRunning: 'Ponto corrido', stitchSatin: 'Ponto cetim', stitchFill: 'Ponto de preenchimento', stitchTatami: 'Preenchimento tatami', stitchRunningNote: 'Contornos leves e letras com pouca cobertura.', stitchSatinNote: 'Colunas e bordas suaves com um caminho de linha concentrado.', stitchFillNote: 'Cobertura sólida que acrescenta linha e esforço de produção.', stitchTatamiNote: 'Preenchimento em camadas com o maior fator de planejamento.', selectStitch: 'Escolha um tipo de ponto', emptyResult: 'Informe um plano para ativar o bastidor.', stitchesUnit: 'pontos equivalentes', minutesUnit: 'minutos', hoursUnit: 'horas', priceUnit: 'unidades monetárias', areaLabel: 'Área bordada', effectiveLabel: 'Pontos equivalentes', stitchTimeLabel: 'Tempo de bordado', productionLabel: 'Tempo de produção', setupLabel: 'Preparação das cores', changesLabel: 'Trocas de cor', basePriceLabel: 'Estimativa base de mão de obra', estimateBadge: 'Estimativa pronta', attentionBadge: 'Revise a escala', warningHighVolume: 'Grande volume de pontos. Faça uma amostra real na máquina antes de orçar.', warningLongRun: 'Produção longa. Verifique separadamente bastidor, quebras de linha e acabamento.', invalidMessage: 'Use valores positivos para tamanho, densidade, velocidade e valor por hora.', formulaTitle: 'O que é contado', formulaText: 'Área vezes densidade ao quadrado cria a base de cobertura. O fator do ponto transforma esse valor em pontos equivalentes, e cada troca depois da primeira cor acrescenta 1,75 minuto.', noteTitle: 'Limite do planejamento', noteText: 'Este é um estimador transparente, não um arquivo de máquina digitalizado nem um orçamento final. Acrescente materiais, preparação, acabamento, despesas, impostos e margem por conta própria.', reset: 'Redefinir exemplo', copied: 'Resumo copiado', copySummary: 'Copiar resumo', canvasAlt: 'Bastidor de tecido com linhas de linha mostrando a densidade atual',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Como estimar pontos e preço de mão de obra de bordado', level: 2 },
  { type: 'paragraph', html: 'Um desenho de bordado traz duas perguntas de planejamento: quanto trabalho de linha existe no motivo e por quanto tempo máquina e operador ficarão ocupados? Este estimador mantém as duas perguntas visíveis e transforma tamanho, densidade, ponto, cores, velocidade e valor por hora em um número comparável.' },
  { type: 'title', text: 'O modelo de pontos', level: 3 },
  { type: 'paragraph', html: 'A base é a área bordada multiplicada pelo quadrado da densidade em pontos por centímetro. Um fator relativo considera a família do ponto: o ponto corrido é mais leve, o cetim é a referência e os preenchimentos são casos de planejamento cada vez mais densos. É uma estimativa do trabalho equivalente, não a contagem exata exportada por um programa de digitalização.' },
  { type: 'table', headers: ['Entrada', 'O que muda', 'O que não promete'], rows: [['Largura e altura', 'Área de cobertura e pontos básicos', 'O contorno exato de um arquivo digitalizado'], ['Densidade e tipo de ponto', 'Trabalho de linha equivalente e tempo de máquina', 'Uma configuração de qualidade universal para todo tecido'], ['Cores', 'Tempo de troca depois da primeira cor', 'A quantidade de cortes ou quebras de linha'], ['Velocidade e valor', 'Duração da produção e valor da mão de obra', 'Um orçamento final para o cliente']] },
  { type: 'title', text: 'Transforme uma estimativa em um preço responsável', level: 3 },
  { type: 'paragraph', html: 'O preço exibido multiplica apenas o tempo de trabalho pelo valor por hora. Um orçamento real deve acrescentar digitalização, linha, estabilizador, bastidor, preparação da máquina, amostras, cortes, retrabalho, acabamento, despesas, impostos e margem. Mantenha esses itens explícitos para que uma contagem baixa não esconda uma preparação demorada.' },
  { type: 'tip', title: 'Teste o plano antes de orçar', html: 'Faça uma amostra representativa no tecido e no estabilizador previstos. Compare o tempo e o comportamento da linha com a estimativa e ajuste suas hipóteses locais de velocidade e preparação.' },
  { type: 'title', text: 'Leia o detalhamento da produção', level: 3 },
  { type: 'list', items: ['Pontos equivalentes mostram a carga de cobertura depois da aplicação do fator.', 'Tempo de produção é igual aos pontos equivalentes divididos pela velocidade da máquina.', 'A preparação das cores acrescenta 1,75 minuto por troca depois da primeira.', 'A estimativa base é o tempo total dividido por 60 e multiplicado pelo valor por hora.'] },
] };
