import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'kalkylator-stygnadsantal-pris-broderi';
const title = 'Kalkylator för stygnantal och broderipris';
const description = 'Uppskatta stygnantal, produktionstid och ett grundpris för arbete utifrån motivets storlek, stygntäthet, färger, hastighet och timpris.';
const faq = [
  { question: 'Hur fungerar uppskattningen av stygnantal?', answer: 'Kalkylatorn multiplicerar den broderade ytan med kvadraten av stygntätheten och använder sedan en faktor för stygnsorten. Resultatet är en jämförbar arbetsbelastning, inte en förutsägelse av en maskinfil.' },
  { question: 'Varför ändrar stygnsorten uppskattningen?', answer: 'Löpstygn, satäng, fyllnad och tatami placerar tråden på olika sätt. Den relativa faktorn visar tydligt att tätare täckning kräver mer produktionsarbete.' },
  { question: 'Ändrar antalet färger antalet stygn?', answer: 'Nej. Antalet färger lägger bara till bytestid. Modellen räknar 1,75 minuter för varje byte efter den första färgen som ett planeringsantagande.' },
  { question: 'Är det beräknade priset en offert?', answer: 'Nej. Det är en uppskattning av arbetet utifrån det angivna timpriset. Tråd, stabilisering, digitalisering, förberedelse, efterarbete, omkostnader, skatt och marginal ingår inte.' },
];
const howTo = [
  { name: 'Mät motivet', text: 'Ange den broderade bredden och höjden i centimeter. Använd den sydda ytan och inte hela bågens storlek.' },
  { name: 'Beskriv stygnplanen', text: 'Välj den dominerande stygnsorten, ange tätheten i stygn per centimeter och räkna trådfärgerna.' },
  { name: 'Lägg till produktionsantaganden', text: 'Ange maskinhastigheten i stygn per minut och ditt timpris för arbete. Håll dig till en valuta.' },
  { name: 'Läs planeringsvärdet', text: 'Använd motsvarande stygn, produktionstid, förberedelsetid och grundpris för att jämföra motiv före digitalisering eller offert.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'sv' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Bygg en stygnplan i broderibågen och se produktionsarbetet och arbetsvärdet.', stageLabel: 'Broderibågen', controlsLabel: 'Bygg stygnplanen', resultLabel: 'Grundpris för arbete', widthLabel: 'Motivets bredd', heightLabel: 'Motivets höjd', densityLabel: 'Stygntäthet', stitchLabel: 'Dominerande stygn', coloursLabel: 'Trådfärger', speedLabel: 'Maskinhastighet', rateLabel: 'Timpris', widthHint: 'sydd yta i cm', heightHint: 'sydd yta i cm', densityHint: 'stygn per cm', coloursHint: 'första färgen kräver inget byte', speedHint: 'stygn per minut', rateHint: 'din valuta per timme', stitchRunning: 'Löpstygn', stitchSatin: 'Satängstygn', stitchFill: 'Fyllnadssöm', stitchTatami: 'Tatamifyllning', stitchRunningNote: 'Lätta konturer och bokstäver med låg täckning.', stitchSatinNote: 'Släta kolumner och kanter med en fokuserad trådbana.', stitchFillNote: 'Solid täckning som ökar trådåtgång och produktionsarbete.', stitchTatamiNote: 'Lagerfyllning med modellens högsta planeringsfaktor.', selectStitch: 'Välj en stygnsort', emptyResult: 'Ange en stygnplan för att aktivera bågen.', stitchesUnit: 'motsvarande stygn', minutesUnit: 'minuter', hoursUnit: 'timmar', priceUnit: 'valutaenheter', areaLabel: 'Broderad yta', effectiveLabel: 'Motsvarande stygn', stitchTimeLabel: 'Stygnstid', productionLabel: 'Produktionstid', setupLabel: 'Färgförberedelse', changesLabel: 'Färgbyten', basePriceLabel: 'Grundpris för arbete', estimateBadge: 'Uppskattning klar', attentionBadge: 'Kontrollera skalan', warningHighVolume: 'Stort stygnantal. Gör ett riktigt maskinprov före offert.', warningLongRun: 'Lång produktion. Kontrollera bågning, trådbrott och efterarbete separat.', invalidMessage: 'Använd positiva värden för storlek, täthet, hastighet och timpris.', formulaTitle: 'Det som räknas', formulaText: 'Yta gånger täthet i kvadrat ger en täckningsbas. Stygnfaktorn omvandlar den till motsvarande stygn och varje byte efter den första färgen lägger till 1,75 minuter.', noteTitle: 'Planeringsgräns', noteText: 'Detta är en transparent uppskattning, inte en digitaliserad maskinfil eller en färdig offert. Lägg själv till material, förberedelse, efterarbete, omkostnader, skatt och marginal.', reset: 'Återställ exempel', copied: 'Sammanfattning kopierad', copySummary: 'Kopiera sammanfattning', canvasAlt: 'Broderibåge av tyg med trådlinjer som visar aktuell täthet',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Så uppskattar du stygnantal och arbetspris för broderi', level: 2 },
  { type: 'paragraph', html: 'Ett broderimotiv har två planeringsfrågor: hur mycket trådarbete motivet innehåller och hur länge maskin och operatör blir upptagna. Den här kalkylatorn håller båda synliga och omvandlar storlek, täthet, stygn, färger, hastighet och timpris till ett jämförbart planeringsvärde.' },
  { type: 'title', text: 'Modellen för stygnantal', level: 3 },
  { type: 'paragraph', html: 'Basen är den broderade ytan multiplicerad med kvadraten av tätheten i stygn per centimeter. En relativ faktor tar hänsyn till stygnfamiljen: löpstygn är lättare, satäng är referensen och fyllnad och tatami är allt tätare planeringsfall. Det är en uppskattning av motsvarande arbete, inte det exakta antal som ett digitaliseringsprogram exporterar.' },
  { type: 'table', headers: ['Inmatning', 'Detta ändras', 'Detta utlovas inte'], rows: [['Bredd och höjd', 'Täckningsyta och basstygn', 'Den exakta konturen i en digitaliserad fil'], ['Täthet och stygnsort', 'Motsvarande trådarbete och maskintid', 'En universell kvalitetsinställning för alla tyger'], ['Färger', 'Bytestid efter första färgen', 'Antalet trådklipp eller trådbrott'], ['Hastighet och timpris', 'Produktionslängd och arbetsvärde', 'En slutlig kundoffert']] },
  { type: 'title', text: 'Gör uppskattningen till ett ansvarsfullt pris', level: 3 },
  { type: 'paragraph', html: 'Det visade priset är bara arbetstid multiplicerad med timpriset. En riktig offert bör lägga till digitalisering, tråd, stabilisering, uppspänning, maskininställning, provbitar, klippning, omarbete, efterarbete, omkostnader, skatt och marginal. Håll posterna synliga så att ett lågt stygnantal inte döljer en lång förberedelse.' },
  { type: 'tip', title: 'Testa planen före offert', html: 'Kör ett representativt prov på avsett tyg och stabilisering. Jämför tid och trådbeteende med uppskattningen och justera dina lokala antaganden om hastighet och förberedelse.' },
  { type: 'title', text: 'Läs produktionsuppdelningen', level: 3 },
  { type: 'list', items: ['Motsvarande stygn visar täckningsarbetet efter att stygnfaktorn har använts.', 'Produktionstid är motsvarande stygn delat med maskinhastigheten.', 'Färgförberedelse lägger till 1,75 minuter för varje byte efter det första.', 'Grundpriset är den totala tiden delad med 60 och multiplicerad med timpriset.'] },
] };
