import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { EmbroideryStitchPricingEstimatorUI } from '../ui';

const slug = 'nakis-dikis-sayisi-fiyat-tahminleyici';
const title = 'Nakış dikiş sayısı ve fiyat tahminleyici';
const description = 'Tasarım boyutu, dikiş yoğunluğu, renk sayısı, hız ve saatlik ücrete göre nakış dikiş sayısını, üretim süresini ve temel işçilik bedelini tahmin edin.';
const faq = [
  { question: 'Nakış dikiş sayısı tahmini nasıl çalışır?', answer: 'Tahminleyici, işlenen alanı dikiş yoğunluğunun karesiyle çarpar ve ardından dikiş türü katsayısını uygular. Sonuç, üretim yükünü karşılaştırmak içindir; makine dosyasının tahmini değildir.' },
  { question: 'Dikiş türü tahmini neden değiştirir?', answer: 'Kontur, saten, dolgu ve tatami dikişleri ipliği farklı biçimlerde yerleştirir. Göreli katsayı, daha yoğun kaplamanın daha fazla üretim emeği istediğini açıkça gösterir.' },
  { question: 'Renk sayısı dikiş sayısını değiştirir mi?', answer: 'Hayır. Renk sayısı yalnızca renk değişim süresi ekler. Model, ilk renkten sonraki her değişim için planlama varsayımı olarak 1,75 dakika ekler.' },
  { question: 'Hesaplanan fiyat teklif midir?', answer: 'Hayır. Girilen saatlik ücrete göre temel işçilik tahminidir. İplik, tela, dijitalleştirme, hazırlık, bitirme, genel gider, vergi ve kâr dahil değildir.' },
];
const howTo = [
  { name: 'Tasarımı ölçün', text: 'İşlenecek genişlik ve yüksekliği santimetre olarak girin. Kasnağın tamamı yerine dikiş uygulanacak alanı kullanın.' },
  { name: 'Dikiş planını tanımlayın', text: 'Baskın dikiş türünü seçin, santimetre başına yoğunluğu girin ve iplik renklerini sayın.' },
  { name: 'Üretim varsayımlarını ekleyin', text: 'Dakikadaki dikiş sayısını ve saatlik işçilik ücretinizi girin. Tek bir para birimi kullanın.' },
  { name: 'Planlama tahminini okuyun', text: 'Dijitalleştirme veya teklif öncesinde tasarımları eşdeğer dikiş, üretim süresi, hazırlık süresi ve temel fiyatla karşılaştırın.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'tr' };
const ui: EmbroideryStitchPricingEstimatorUI = {
  intro: 'Kasnak içindeki dikiş planınızı oluşturun, üretim yükünü ve işçilik değerini görün.', stageLabel: 'Dikiş kasnağı', controlsLabel: 'Dikiş planını oluşturun', resultLabel: 'Temel işçilik tahmini', widthLabel: 'Tasarım genişliği', heightLabel: 'Tasarım yüksekliği', densityLabel: 'Dikiş yoğunluğu', stitchLabel: 'Baskın dikiş', coloursLabel: 'İplik renkleri', speedLabel: 'Makine hızı', rateLabel: 'Saatlik ücret', widthHint: 'işlenen alan cm', heightHint: 'işlenen alan cm', densityHint: 'cm başına dikiş', coloursHint: 'ilk renk değişim gerektirmez', speedHint: 'dakikadaki dikiş', rateHint: 'saat başına para biriminiz', stitchRunning: 'Kontur dikişi', stitchSatin: 'Saten dikiş', stitchFill: 'Dolgu dikişi', stitchTatami: 'Tatami dolgusu', stitchRunningNote: 'Düşük kaplamalı hafif konturlar ve yazılar.', stitchSatinNote: 'Odaklanmış iplik yolu olan düzgün sütunlar ve kenarlar.', stitchFillNote: 'İplik ve üretim emeğini artıran yoğun kaplama.', stitchTatamiNote: 'Bu modeldeki en yüksek planlama katsayısına sahip katmanlı dolgu.', selectStitch: 'Dikiş türü seçin', emptyResult: 'Kasnağı etkinleştirmek için bir dikiş planı girin.', stitchesUnit: 'eşdeğer dikiş', minutesUnit: 'dakika', hoursUnit: 'saat', priceUnit: 'para birimi', areaLabel: 'İşlenen alan', effectiveLabel: 'Eşdeğer dikişler', stitchTimeLabel: 'Dikiş süresi', productionLabel: 'Üretim süresi', setupLabel: 'Renk hazırlığı', changesLabel: 'Renk değişimleri', basePriceLabel: 'Temel işçilik tahmini', estimateBadge: 'Tahmin hazır', attentionBadge: 'Ölçeği inceleyin', warningHighVolume: 'Dikiş hacmi yüksek. Teklif vermeden önce gerçek makine numunesi alın.', warningLongRun: 'Üretim süresi uzun. Kasnaklama, iplik kopmaları ve bitirme süresini ayrıca kontrol edin.', invalidMessage: 'Boyut, yoğunluk, hız ve saatlik ücret için pozitif değerler kullanın.', formulaTitle: 'Neler hesaplanır', formulaText: 'Alan ile yoğunluğun karesi kaplama tabanını oluşturur. Dikiş katsayısı bunu eşdeğer dikişlere çevirir ve ilk renkten sonraki her değişim 1,75 dakika ekler.', noteTitle: 'Planlama sınırı', noteText: 'Bu şeffaf bir tahmin aracıdır; dijitalleştirilmiş makine dosyası veya son teklif değildir. Malzeme, hazırlık, bitirme, genel gider, vergi ve kârı ayrıca ekleyin.', reset: 'Örneği sıfırla', copied: 'Özet kopyalandı', copySummary: 'Özeti kopyala', canvasAlt: 'Güncel yoğunluğu iplik çizgileriyle gösteren kumaş nakış kasnağı',
};
export const content: ToolLocaleContent<EmbroideryStitchPricingEstimatorUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Nakış dikiş sayısı ve işçilik fiyatı nasıl tahmin edilir', level: 2 },
  { type: 'paragraph', html: 'Bir nakış tasarımında iki planlama sorusu vardır: motifte ne kadar iplik işi bulunur ve makine ile operatör ne kadar süre meşgul olur? Bu tahminleyici iki konuyu görünür tutar ve boyut, yoğunluk, dikiş, renk, hız ve ücreti karşılaştırılabilir bir planlama değerine dönüştürür.' },
  { type: 'title', text: 'Dikiş sayısı modeli', level: 3 },
  { type: 'paragraph', html: 'Temel değer, işlenen alanın santimetre başına dikiş yoğunluğunun karesiyle çarpılmasıdır. Göreli katsayı dikiş ailesini hesaba katar: kontur daha hafif, saten referans, dolgu ve tatami ise giderek yoğunlaşan planlama durumlarıdır. Bu, eşdeğer iş yükü tahminidir; dijitalleştirme yazılımının verdiği kesin sayı değildir.' },
  { type: 'table', headers: ['Girdi', 'Neyi değiştirir', 'Neyi garanti etmez'], rows: [['Genişlik ve yükseklik', 'Kaplama alanı ve temel dikiş sayısı', 'Dijital dosyanın kesin dış çizgisi'], ['Yoğunluk ve dikiş türü', 'Eşdeğer iplik işi ve makine süresi', 'Her kumaş için evrensel kalite ayarı'], ['Renkler', 'İlk renkten sonraki değişim süresi', 'Kesim veya iplik kopması sayısı'], ['Hız ve ücret', 'Üretim süresi ve işçilik değeri', 'Müşteriye verilecek son teklif']] },
  { type: 'title', text: 'Tahmini sorumlu bir fiyata dönüştürün', level: 3 },
  { type: 'paragraph', html: 'Gösterilen fiyat yalnızca çalışma süresinin saatlik ücretle çarpımıdır. Gerçek bir teklif dijitalleştirme, iplik, tela, kasnaklama, makine hazırlığı, numune, kesim, yeniden işleme, bitirme, genel gider, vergi ve kârı eklemelidir. Düşük dikiş sayısının uzun hazırlığı gizlememesi için kalemleri ayrı tutun.' },
  { type: 'tip', title: 'Tekliften önce planı test edin', html: 'Kullanılacak kumaş ve tela üzerinde temsilî bir numune çalıştırın. Süreyi ve iplik davranışını tahminle karşılaştırıp yerel hız ve hazırlık varsayımlarınızı ayarlayın.' },
  { type: 'title', text: 'Üretim dökümünü okuma', level: 3 },
  { type: 'list', items: ['Eşdeğer dikişler, katsayı uygulandıktan sonraki kaplama işini gösterir.', 'Üretim süresi, eşdeğer dikişlerin makine hızına bölünmesidir.', 'Renk hazırlığı ilk renkten sonraki her değişim için 1,75 dakika ekler.', 'Temel işçilik tahmini, toplam sürenin 60a bölünüp saatlik ücretle çarpılmasıdır.'] },
] };
