import type { SizeData, MeasurementRange } from './logic';

export interface ClothingSizeConverterUI {
  categoryLabel: string;
  categoryShirts: string;
  categoryPants: string;
  categoryDresses: string;
  categoryJackets: string;
  genderLabel: string;
  genderMen: string;
  genderWomen: string;
  genderUnisex: string;
  tabBySize: string;
  tabByMeasurements: string;
  regionLabel: string;
  sizeLabel: string;
  regionEU: string;
  regionUS: string;
  regionUK: string;
  regionIT: string;
  labelEU: string;
  labelUS: string;
  labelUK: string;
  labelIT: string;
  quickGridTitle: string;
  tableTitle: string;
  measurementsTitle: string;
  chestLabel: string;
  waistLabel: string;
  hipLabel: string;
  chestPlaceholder: string;
  waistPlaceholder: string;
  hipPlaceholder: string;
  recommendBtnLabel: string;
  tipsTitle: string;
  tipOverClothes: string;
  tipStraight: string;
  tipNoTight: string;
  tipEndOfDay: string;
  recommendationTitle: string;
  recommendedSizePrefix: string;
  measuredBy: string;
  chestShort: string;
  waistShort: string;
  hipShort: string;
  recommendationError: string;
  recommendationNoData: string;
  fitGuideTitle: string;
  fitSmall: string;
  fitRegular: string;
  fitLarge: string;
  fitInfoDefault: string;
  fitNotif1: string;
  fitNotifSmall: string;
  fitNotifRegular: string;
  fitNotifLarge: string;
  fitNotif2: string;
  fitNotif3: string;
  fitAdviceSmall: string;
  fitAdviceRegular: string;
  fitAdviceLarge: string;
  fitSelectedSuffix: string;
  infoBannerTitle: string;
  infoBannerText: string;
  shirtsData: Record<string, SizeData[]>;
  pantsData: Record<string, SizeData[]>;
  dressesData: Record<string, SizeData[]>;
  jacketsData: Record<string, SizeData[]>;
  measurementRanges: Record<string, MeasurementRange[]>;
}
