import type { TextileData } from './logic';

export const TEXTILE_CARE_DATA_EN: Record<string, TextileData> = {
  cotton: {
    name: "Cotton",
    description: "Natural plant fiber, soft and breathable. The king of basics.",
    family: "natural",
    origin: "Cotton plant capsule",
    breathability: 9,
    durability: 7,
    warmth: 4,
    washing: "Cold or lukewarm water (shrinks with heat). Allows strong spinning.",
    drying: "Dryer on medium heat or air dry.",
    ironing: "High heat with steam while still damp.",
    donts: ["Leave wet for long (mold risk)", "Excess bleach (weakens fibers)"],
    sos: "Shrunk? Soak in lukewarm water with hair conditioner and gently stretch.",
    icon: "mdi:tshirt-crew",
    color: "#60A5FA",
    maxTemp: "40-60°C",
    isNoble: false,
  },
  linen: {
    name: "Linen",
    description: "Very strong plant fiber, fresh and with characteristic wrinkle.",
    family: "natural",
    origin: "Linen plant stem",
    breathability: 10,
    durability: 9,
    warmth: 2,
    washing: "Delicate cycle, don't overfill drum (needs water to avoid breaking).",
    drying: "Air dry only. NEVER use dryer (breaks fibers).",
    ironing: "Maximum temperature, always with very damp garment.",
    donts: ["Strong spinning", "Always folding same way (fibers break)"],
    sos: "Shine from ironing? Wipe with cloth dampened in white vinegar.",
    icon: "mdi:leaf",
    color: "#A7F3D0",
    maxTemp: "60°C",
    isNoble: true,
  },
  wool: {
    name: "Wool / Merino",
    description: "Protein fiber, excellent thermal insulator and elastic.",
    family: "natural",
    origin: "Sheep fleece",
    breathability: 8,
    durability: 6,
    warmth: 10,
    washing: "Hand wash or wool cycle. Neutral soap. NEVER hot water (felts).",
    drying: "Flat on towel. Never hang (deforms).",
    ironing: "Vertical steam or medium heat with cloth on top.",
    donts: ["Hot water", "Rubbing or wringing", "Bleach (dissolves)"],
    sos: "Felted? Almost impossible, but soaking with conditioner may help slightly.",
    icon: "mdi:sheep",
    color: "#FCD34D",
    maxTemp: "30°C",
    isNoble: true,
  },
  silk: {
    name: "Silk",
    description: "Continuous filament animal fiber. Natural sheen and dry feel.",
    family: "natural",
    origin: "Silkworm cocoon",
    breathability: 7,
    durability: 5,
    warmth: 6,
    washing: "Hand wash in cold water with neutral shampoo. Don't wring.",
    drying: "Roll in towel to remove moisture. Air dry in shade.",
    ironing: "Low heat, inside out, no direct steam.",
    donts: ["Direct sunlight (burns)", "Perfume/Deodorant (stains)", "Water (water marks)"],
    sos: "Water stain? Gently rub silk against itself.",
    icon: "mdi:ticket-percent",
    color: "#F472B6",
    maxTemp: "20°C",
    isNoble: true,
  },
  cashmere: {
    name: "Cashmere",
    description: "Luxury fiber from Cashmere goat. Extremely soft and warm.",
    family: "natural",
    origin: "Undercoat of Hircus goat",
    breathability: 9,
    durability: 5,
    warmth: 10,
    washing: "STRICTLY hand wash with baby shampoo. Cold water. Never rub.",
    drying: "Flat on towel, shaping as it dries. Never hang.",
    ironing: "Vertical steam without touching or mild heat with cloth.",
    donts: ["Washing machine (even wool cycle)", "Fabric softener", "Continuous friction (pilling)"],
    sos: "Pilling? Use specialized comb or remove by hand.",
    icon: "mdi:crown",
    color: "#F59E0B",
    maxTemp: "20°C",
    isNoble: true,
  },
  polyester: {
    name: "Polyester",
    description: "Synthetic petroleum fiber. Resistant, wrinkle-free, doesn't breathe.",
    family: "synthetic",
    origin: "Petroleum-derived polymers",
    breathability: 2,
    durability: 10,
    warmth: 5,
    washing: "Warm/cold water. Tolerates everything, but traps odors and oils.",
    drying: "Low dryer or air dry. Dries very quickly.",
    ironing: "Low/medium heat. Be careful, it melts.",
    donts: ["Excess heat", "Fabric softener (creates waxy film that traps odor)"],
    sos: "Persistent odor? Soak in water with vinegar before washing.",
    icon: "mdi:oil",
    color: "#94A3B8",
    maxTemp: "40°C",
    isNoble: false,
  },
  viscose: {
    name: "Viscose / Rayon",
    description: "Semi-synthetic regenerated cellulose. Silky feel, very absorbent.",
    family: "artificial",
    origin: "Chemically treated wood pulp",
    breathability: 8,
    durability: 4,
    warmth: 3,
    washing: "Delicate in cold. Becomes very weak when wet.",
    drying: "Flat or padded hanger. No dryer.",
    ironing: "Medium, inside out. No direct steam if possible.",
    donts: ["Wring when wet (breaks)", "Long soaks"],
    sos: "Shrunken and stiff? Iron with lots of steam to relax fibers.",
    icon: "mdi:forest",
    color: "#C084FC",
    maxTemp: "30°C",
    isNoble: false,
  },
  nylon: {
    name: "Nylon (Polyamide)",
    description: "Highly resistant to tension and abrasion.",
    family: "synthetic",
    origin: "Petroleum-derived (polyamide)",
    breathability: 3,
    durability: 10,
    warmth: 4,
    washing: "Normal cycle. Be careful mixing colors (absorbs dyes).",
    drying: "Air dry. Low dryer.",
    ironing: "Very low. Melts quickly.",
    donts: ["Bleach (yellows)", "Direct sunlight (fades)"],
    sos: "Grayish? Wash with oxygen-based whitener.",
    icon: "mdi:parachute",
    color: "#2DD4BF",
    maxTemp: "40°C",
    isNoble: false,
  },
  acrylic: {
    name: "Acrylic",
    description: "Synthetic wool imitation. Soft, warm, pills easily.",
    family: "synthetic",
    origin: "Polyacrylonitrile",
    breathability: 4,
    durability: 6,
    warmth: 8,
    washing: "Lukewarm water. Use fabric softener to reduce static.",
    drying: "Air dry. Heat permanently deforms garment.",
    ironing: "Don't iron",
    donts: ["Fabric softener (breaks fibers)", "Strong wringing", "Heat"],
    sos: "Lost elasticity? It's irreversible (fibers are broken).",
    icon: "mdi:resize",
    color: "#450A0A",
    maxTemp: "30°C",
    isNoble: false,
  },
};
