import type { TextileData } from './logic';

export const TEXTILE_CARE_DATA_FR: Record<string, TextileData> = {
  cotton: {
    name: 'Coton',
    icon: 'mdi:tshirt-crew',
    color: '#60A5FA',
    maxTemp: '40-60°C',
    ironing: 'Élevé',
    drying: 'Sèche-linge OK',
    donts: ['Eau de Javel (sauf blanc)', 'Séchage excessif'],
    sos: 'Tache de graisse ? Appliquez du bicarbonate de soude avant de laver.',
    description: 'Fibre naturelle résistante et respirante. Le roi du confort quotidien.',
  },
  linen: {
    name: 'Lin',
    icon: 'mdi:leaf',
    color: '#A7F3D0',
    maxTemp: '30-40°C',
    ironing: 'Très Élevé (Humide)',
    drying: 'À l\'ombre',
    donts: ['Essorage fort', 'Plier toujours au même endroit'],
    sos: 'Repassez pendant que le tissu est encore légèrement humide.',
    description: 'Fibre végétale très fraîche. Se froisse avec élégance.',
  },
  wool: {
    name: 'Laine / Mérino',
    icon: 'mdi:sheep',
    color: '#FCD34D',
    maxTemp: 'Froid / Laine',
    ironing: 'Vapeur uniquement',
    drying: 'À plat',
    donts: ['Eau chaude', 'Agitation forte', 'Sèche-linge'],
    sos: 'Besoin d\'un rafraîchissement ? Suspendez-la dans la salle de bain pendant que vous vous douchez.',
    description: 'Fibre animale thermorégulatrice. N\'a pas besoin de lavages fréquents.',
  },
  silk: {
    name: 'Soie',
    icon: 'mdi:ticket-percent',
    color: '#F472B6',
    maxTemp: 'Main / Froid',
    ironing: 'Bas (Envers)',
    drying: 'À plat / Ombre',
    donts: ['Lumière directe du soleil', 'Parfum/Déodorant', 'Eau (fait des cernes)'],
    sos: 'Tache d\'eau ? Frottez doucement la soie contre elle-même.',
    description: 'Fibre animale en filament continu. Brillance naturelle et toucher sec.',
  },
  cashmere: {
    name: 'Cachemire',
    icon: 'mdi:crown',
    color: '#F59E0B',
    maxTemp: 'Main / Froid',
    ironing: 'Vapeur / Bas',
    drying: 'À plat sur serviette',
    donts: ['Suspendre (se déforme)', 'Frotter fort'],
    sos: 'Enroulez dans une serviette pour enlever l\'humidité. Séchez à l\'ombre.',
    description: 'Laine ultra-fine et luxueuse. Très délicate mais extrêmement chaude.',
  },
  polyester: {
    name: 'Polyester',
    icon: 'mdi:oil',
    color: '#94A3B8',
    maxTemp: '30-40°C',
    ironing: 'Bas',
    drying: 'Rapide / Sèche-linge bas',
    donts: ['Température élevée (fond)', 'Repassage direct sans vapeur'],
    sos: 'Utilisez un adoucissant pour réduire l\'électricité statique.',
    description: 'Fibre synthétique dérivée du pétrole. Durable et ne se froisse pas.',
  },
  viscose: {
    name: 'Viscosa / Rayonne',
    icon: 'mdi:forest',
    color: '#C084FC',
    maxTemp: '30°C / Délicat',
    ironing: 'Moyen',
    drying: 'À plat',
    donts: ['Essorage fort', 'Tordre quand c\'est mouillé'],
    sos: 'Elle rétrécit souvent au lavage mais retrouve sa forme au repassage.',
    description: 'Fibre artificielle d\'origine cellulosique. Douce et avec beaucoup de drapé.',
  },
  nylon: {
    name: 'Nylon (Polyamide)',
    icon: 'mdi:parachute',
    color: '#2DD4BF',
    maxTemp: '30°C',
    ironing: 'Très Bas',
    drying: 'Air libre',
    donts: ['Sèche-linge chaud', 'Eau de Javel'],
    sos: 'Lavez dans un sac en filet pour éviter les accrocs.',
    description: 'Fibre synthétique très résistante et élastique. Séchage ultra-rapide.',
  },
  acrylic: {
    name: 'Acrylique',
    icon: 'mdi:resize',
    color: '#450A0A',
    maxTemp: '30°C',
    ironing: 'Froid / Non',
    drying: 'À plat',
    donts: ['Chaleur directe', 'Vapeur excessive'],
    sos: 'Lavez à l\'envers pour éviter la formation de boulettes.',
    description: 'Fibre synthétique imitant la laine. Chaude mais peu respirante.',
  },
};
