import type { TextileData } from './logic';

export const TEXTILE_CARE_DATA_ES: Record<string, TextileData> = {
  cotton: {
    name: "Algodón",
    description: "Fibra vegetal natural, suave y transpirable. El rey de los básicos.",
    family: "natural",
    origin: "Cápsula de la planta de algodón",
    breathability: 9,
    durability: 7,
    warmth: 4,
    washing: "Agua fría o templada (encoge con calor). Permite centrifugado fuerte.",
    drying: "Secadora a temp media o aire libre.",
    ironing: "Plancha alta con vapor mientras está húmedo.",
    donts: ["Dejar húmedo mucho tiempo (moho)", "Lejía excesiva (debilita fibra)"],
    sos: "¿Encogido? Remoja en agua tibia con acondicionador para pelo y estira suavemente.",
    icon: "mdi:tshirt-crew",
    color: "#60A5FA",
    maxTemp: "40-60°C",
    isNoble: false,
  },
  linen: {
    name: "Lino",
    description: "Fibra vegetal muy fuerte, fresca y con arruga característica.",
    family: "natural",
    origin: "Tallo de la planta de lino",
    breathability: 10,
    durability: 9,
    warmth: 2,
    washing: "Ciclo delicado, no llenar mucho el tambor (necesita agua para no romperse).",
    drying: "Aire libre. NUNCA secadora (rompe las fibras).",
    ironing: "Plancha máxima temperatura, siempre con la prenda muy húmeda.",
    donts: ["Centrifugado fuerte", "Doblar siempre por el mismo sitio (se corta)"],
    sos: "¿Brillo por planchado? Pasa un paño con vinagre blanco.",
    icon: "mdi:leaf",
    color: "#A7F3D0",
    maxTemp: "60°C",
    isNoble: true,
  },
  wool: {
    name: "Lana / Merino",
    description: "Fibra animal proteica, aislante térmico excelente y elástica.",
    family: "natural",
    origin: "Vellón de oveja",
    breathability: 8,
    durability: 6,
    warmth: 10,
    washing: "A mano o ciclo lana. Jabón neutro. NUNCA agua caliente (se afieltra).",
    drying: "Horizontal sobre toalla. Nunca colgar (se deforma).",
    ironing: "Vapor vertical o plancha media con paño encima.",
    donts: ["Agua caliente", "Frotar o retorcer", "Lejía (la disuelve)"],
    sos: "¿Afieltrada? Casi imposible, pero remojo con suavizante puede relajar algo.",
    icon: "mdi:sheep",
    color: "#FCD34D",
    maxTemp: "30°C",
    isNoble: true,
  },
  silk: {
    name: "Seda",
    description: "Fibra animal de filamento continuo. Brillo natural y tacto seco.",
    family: "natural",
    origin: "Capullo del gusano de seda",
    breathability: 7,
    durability: 5,
    warmth: 6,
    washing: "A mano en agua fría con champú neutro. No retorcer.",
    drying: "Enrollar en toalla para quitar humedad. Secar a la sombra.",
    ironing: "Plancha baja, del revés y sin vapor directo.",
    donts: ["Sol directo (quema)", "Perfume/Desodorante (mancha)", "Agua (hace cercos)"],
    sos: "¿Mancha de agua? Frota suavemente la seda contra sí misma.",
    icon: "mdi:ticket-percent",
    color: "#F472B6",
    maxTemp: "20°C",
    isNoble: true,
  },
  cashmere: {
    name: "Cashmere",
    description: "Fibra de lujo de cabra de Cachemira. Extremadamente suave y cálida.",
    family: "natural",
    origin: "Capa inferior del pelo de la cabra Hircus",
    breathability: 9,
    durability: 5,
    warmth: 10,
    washing: "ESTRICTAMENTE a mano con champú de bebé. Agua fría. Nunca frotar.",
    drying: "Horizontal sobre toalla, dándole forma. Jamás colgar.",
    ironing: "Vapor vertical sin tocar la prenda o plancha tibia con paño.",
    donts: ["Lavadora (incluso programa lana)", "Suavizante", "Roces continuos (bolitas)"],
    sos: "¿Pilling (bolitas)? Usa un peine específico o quítalas a mano.",
    icon: "mdi:crown",
    color: "#F59E0B",
    maxTemp: "20°C",
    isNoble: true,
  },
  polyester: {
    name: "Poliéster",
    description: "Fibra sintética de petróleo. Resistente, no arruga, no respira.",
    family: "synthetic",
    origin: "Polímeros derivados del petróleo",
    breathability: 2,
    durability: 10,
    warmth: 5,
    washing: "Agua tibia/fría. Admite todo, pero atrapa olores y grasas.",
    drying: "Secadora baja o aire. Seca muy rápido.",
    ironing: "Plancha baja/media. Cuidado, se funde.",
    donts: ["Calor excesivo", "Suavizante (crea capa cerosa que atrapa más olor)"],
    sos: "¿Olor persistente? Remojo en agua con vinagre antes de lavar.",
    icon: "mdi:oil",
    color: "#94A3B8",
    maxTemp: "40°C",
    isNoble: false,
  },
  viscose: {
    name: "Viscosa / Rayón",
    description: "Semisintética de celulosa regenerada. Tacto seda, muy absorbente.",
    family: "artificial",
    origin: "Pulpa de madera tratada químicamente",
    breathability: 8,
    durability: 4,
    warmth: 3,
    washing: "Delicado en frío. Se vuelve muy débil mojada.",
    drying: "Horizontal o percha acolchada. No secadora.",
    ironing: "Media, del revés. Sin vapor directo si es posible.",
    donts: ["Retorcer mojada (se rompe)", "Remojos largos"],
    sos: "¿Encogida y dura? Plancha con mucho vapor para relajar la fibra.",
    icon: "mdi:forest",
    color: "#C084FC",
    maxTemp: "30°C",
    isNoble: false,
  },
  nylon: {
    name: "Nailon (Poliamida)",
    description: "Sintética muy resistente a tracción y abrasión.",
    family: "synthetic",
    origin: "Derivado del petróleo (poliamida)",
    breathability: 3,
    durability: 10,
    warmth: 4,
    washing: "Ciclo normal. Cuidado con mezclar colores (los absorbe).",
    drying: "Aire libre. Secadora baja.",
    ironing: "Muy baja. Se funde rapidísimo.",
    donts: ["Lejía (amarillea)", "Secar al sol directo"],
    sos: "¿Grisáceo? Lavar con blanqueador oxigenado.",
    icon: "mdi:parachute",
    color: "#2DD4BF",
    maxTemp: "40°C",
    isNoble: false,
  },
  acrylic: {
    name: "Acrílico",
    description: "Sintético imitación lana. Suave, caliente, hace bolas.",
    family: "synthetic",
    origin: "Poliacupacrilonitrilo",
    breathability: 4,
    durability: 6,
    warmth: 8,
    washing: "Agua templada. Mucho suavizante para estática.",
    drying: "Aire. El calor deforma la prenda permanentemente.",
    ironing: "No planchar",
    donts: ["Suavizante (rompe fibras)", "Escurrir fuerte", "Calor"],
    sos: "Si ha perdido elasticidad, es irreversible (las fibras se han roto).",
    icon: "mdi:resize",
    color: "#450A0A",
    maxTemp: "30°C",
    isNoble: false,
  },
};
